---
- name: include variables for production
  include_vars: production.yml
  when: env == 'production'

- name: include variables for development
  include_vars: development.yml
  when: env == 'development'

- name: install nfs tools for EFS
  apt: name=nfs-common state=present

- name: create jenkins home EFS mountpoint
  mount:
    path: "{{ jenkins_home_dir }}"
    src: "{{ aws_efs_dns_name }}:/"
    fstype: nfs4
    opts: rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
    state: present

- name: install docker
  apt: name=docker.io state=present

- name: enable docker
  systemd: name=docker enabled=yes state=started

- name: install jenkins group
  group: name=jenkins gid={{ jenkins_gid }} system=yes state=present

- name: install jenkins user
  user: name=jenkins uid={{ jenkins_uid }} groups=docker home="{{ jenkins_home_dir }}" system=yes state=present

- name: create jenkins home
  file: dest="{{ jenkins_home_dir }}" mode=0550 owner=jenkins group=jenkins state=directory

- name: add java apt repo
  apt_repository: repo=ppa:webupd8team/java update_cache=yes

- name: accept the Oracle v1.1 license
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections

- name: mark Oracle v1.1 license as seen
  shell: echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections

- name: install oracle java
  apt: name=oracle-java8-installer state=present

- name: add jenkins repo key
  apt_key:
    url: "https://pkg.jenkins.io/debian/jenkins.io.key"
    state: present

- name: add jenkins repo key
  apt_repository:
    repo: deb http://pkg.jenkins.io/debian-stable binary/
    state: present

- name: install jenkins
  apt: name=jenkins state=present

- name: set JENKINS_HOME
  lineinfile:
    path: /etc/default/jenkins
    regexp: "^JENKINS_HOME="
    line: JENKINS_HOME={{ jenkins_home_dir }}

- name: enable jenkins
  systemd: name=jenkins enabled=yes state=started
