---
- name: install nfs tools for EFS
  apt: name=nfs-common state=present

- name: create jenkins home EFS mountpoint
  mount:
    path: "{{ jenkins_home_dir }}"
    src: "{{ aws_efs_dns_name }}:/"
    fstype: nfs4
    opts: rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
    state: present

